package com.hebee.bookswap.constant;

public enum ExchangeEventType {
    EXCHANGE_CREATED,
    EXCHANGE_ACCEPTED,
    EXCHANGE_REJECTED,
    RETURN_REQUESTED,
    RETURN_ACCEPTED,
    RETURN_DECLINED,
    RETURN_STARTED,
    RETURN_OTP_GENERATED,
    RETURN_OTP_REGENERATED,
    RETURN_OTP_VERIFIED,
    RETURN_OTP_EXPIRED,
    RETURN_OTP_LOCKED,
    BOOK_RETURNED,
    OWNER_CONFIRMED,
    EXCHANGE_COMPLETED
}
